name: Build module & upload artifact
on:
  push:
    branches:
      - 'main'
      -
jobs:
  deploy:
    name: Build dependencies & create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Install production dependencies
        run: |
          composer install --no-dev

      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v2.0
        with:
          paths: ${{ steps.vars.outputs.excluded }}

      - name: Create & upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ github.event.repository.name }}
          path: '../'